server:
  port: ${SERVER_PORT}

jwt:
  secret: ${JWT_SECRET}

chatting:
  server:
    url: ${SERVER_URL}

redis:
  host: ${REDIS_HOST}
  port: ${REDIS_PORT}

logging:
  level:
    org.springframework.web.socket: DEBUG
    org.springframework.messaging.simp: DEBUG